GEMINYS.WEB/Controllers/PerfilUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GEMINYS.WEB.Models.BackOffice;
using GEMINYS.WEB.Models;
using Geminys.BLL;

namespace GEMINYS.WEB.Controllers
{
    public class PerfilUsuarioController : Controller
    {
        [HttpGet]
        public ActionResult AltaPerfil(string nombre)
        {
            //PerfilUsuario.
            PerfilBLL obj = new PerfilBLL();
            int resultado = obj.AddPerfil(nombre);
           
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Perfil()
        {
            //PerfilModel modeloPerfil = new PerfilModel();
            return View();
        }

        [HttpGet]
        public JsonResult GetMenuPerfiles(string strPerfil)
        {
            PerfilModel modelPerfil = new PerfilModel();
            MenuItemBLL objMenuItemBLL = new MenuItemBLL();
            // Si es nulo, obtiene toda la lista de menu
            if (string.IsNullOrEmpty(strPerfil))
            {
                modelPerfil.listadoMenuByPerfil = modelPerfil.getListaMenuByPerfil(0);
                //modelPerfil.listadoMenuPerfil = modelPerfil.getListaMenu(objMenuItemBLL.GetAllMenu());             
               // modelPerfil.listadoPerfiles = modelPerfil.getListaPerfiles();
            }
            else
            {
                //solo lista de menu por Perfil 
                modelPerfil.listadoMenuByPerfil = modelPerfil.getListaMenuByPerfil(Convert.ToInt32(strPerfil));
            }  
            return Json(modelPerfil, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AltaPerfilMenu(string strPerfilMenu, string strPerfil)
        {
            //PerfilUsuario.
            PerfilBLL obj = new PerfilBLL();
            int resultado = obj.AddPerfilMenu(strPerfilMenu, Convert.ToInt32(strPerfil));

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

    }
}

GEMINYS.WEB/Controllers/UsuarioController.cs
using Geminys.BLL;
using Geminys.BLL.Menus;
using GEMINYS.WEB.Models;
using GEMINYS.WEB.Models.BackOffice;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GEMINYS.WEB.Controllers
{
    public class UsuarioController : Controller
    {
      
        [HttpPost]
        public ActionResult MantenimientoUsuario(UsuarioModel modeloUsuario)
        {

            return View(modeloUsuario);
        }

        [HttpGet]
        public ActionResult MantenimientoUsuario()
        {
            UsuarioModel modeloUsuario = new UsuarioModel();
            UsuarioBLL objUsuario = new UsuarioBLL();
            modeloUsuario.listadoUsuarios =  modeloUsuario.getListaUsuarios(objUsuario.GetListaUsuarios());
            return View(modeloUsuario);
        }

        /// <summary>
        /// Accion que retorna los usuarios segun el criterio de busqueda
        /// </summary>
        /// <param name="modeloUsuario"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult BuscarUsuarios(UsuarioModel busquedaUsuario)
        {
    
            UsuarioBLL objUsuario = new UsuarioBLL();
            busquedaUsuario.listadoUsuarios = busquedaUsuario.getListaUsuarios(objUsuario.FindUsuarios(busquedaUsuario.nombre,busquedaUsuario.apellido1,busquedaUsuario.apellido2, busquedaUsuario.dne,busquedaUsuario.activo));
            return View("MantenimientoUsuario", busquedaUsuario);
        }
        /// <summary>
        /// Accion que gestiona el alta de un usuario
        /// </summary>
        /// <param name="nombre"></param>
        /// <param name="apellido1"></param>
        /// <param name="apellido2"></param>
        /// <param name="dne"></param>
        /// <param name="tip"></param>
        /// <param name="empresa"></param>
        /// <param name="perfil"></param>
        /// <param name="telefono"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult AltaUsuario(string nombre, string apellido1,string apellido2,string dne,string tip,string empresa,string perfil,string telefono)
        {
            bool resultadoAlta = UsuarioBLL.AltaUsuario(nombre, apellido1, apellido2, dne, tip, empresa, perfil, telefono);
            return Json(resultadoAlta, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Accion que gestiona la modificacion de un usuario
        /// </summary>
        /// <param name="nombre"></param>
        /// <param name="apellido1"></param>
        /// <param name="apellido2"></param>
        /// <param name="dne"></param>
        /// <param name="tip"></param>
        /// <param name="empresa"></param>
        /// <param name="perfil"></param>
        /// <param name="telefono"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult ModificacionUsuario(string nombre, string apellido1, string apellido2, string dne, string tip, string empresa, string perfil, string telefono)
        {
            bool resultadoModificacion = UsuarioBLL.ModificacionUsuario(nombre, apellido1, apellido2, dne, tip, empresa, perfil, telefono);
            return Json(resultadoModificacion, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Metodo que activa o desactiva un usuario
        /// </summary>
        /// <param name="idUsuario"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult ActivarDesactivarUsuario(string idUsuario,string operacion)
        {
            bool resultadoOperacion = UsuarioBLL.ActivarDesactivarUsuario(idUsuario,operacion);
            return Json(resultadoOperacion, JsonRequestBehavior.AllowGet);
        }



        /// <summary>
        /// Accion que retorna el listado de empresas asociadas a METRO
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult ListaEmpresas()
        {
            EmpresaModel modeloEmpresa = new EmpresaModel();
            modeloEmpresa.listaEmpresas = modeloEmpresa.getListaEmpresas(CombosBLL.getEmpresas());
            return Json(modeloEmpresa.listaEmpresas, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Accion que retorna el listado de perfiles asociados a usuarios
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult ListaPerfiles()
        {
            PerfilModel modeloPerfil = new PerfilModel();
            modeloPerfil.listaPerfiles = modeloPerfil.getListaPerfil(CombosBLL.getPerfiles());
            return Json(modeloPerfil.listaPerfiles, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Accion que retorna un listado con los usuarios conectados
        /// </summary>
        /// <returns></returns>
                 
        [HttpGet]
        public ActionResult UsuariosConectados() {

            UsuarioConectadoModel modeloUsuarioConectado = new UsuarioConectadoModel();
            UsuarioBLL objUsuario = new UsuarioBLL();
            modeloUsuarioConectado.listadoUsuarios = modeloUsuarioConectado.findUsuariosConectados(objUsuario.FindUsuariosConectados(string.Empty));
            return View(modeloUsuarioConectado);

        }
        /// <summary>
        ///  
        /// </summary>
        /// <param name="fecha"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetUsuariosConectados(string fecha)
        {
            UsuarioConectadoModel modeloUsuarioConectado = new UsuarioConectadoModel();
            UsuarioBLL objUsuario = new UsuarioBLL();
            modeloUsuarioConectado.listadoUsuarios = modeloUsuarioConectado.findUsuariosConectados(objUsuario.FindUsuariosConectados(fecha));
            return Json(modeloUsuarioConectado, JsonRequestBehavior.AllowGet);
        }


    }
}

GEMINYS.WEB/Views/PerfilUsuario/Perfil.cshtml
@model GEMINYS.WEB.Models.BackOffice.PerfilModel

@{
    ViewBag.Title = "Perfil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>

<body>
    <br>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-primary ">
            <div class="panel-heading">Perfiles de Usuarios</div>
            <div class="panel-body ">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 " style="padding-left:15%;">
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                        <div class="panel panel-primary ">
                            <div class="panel-heading">Perfiles</div>
                            <div class="panel-body">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="table-responsive">
                                        <table class="table tabla-sinbordes ">
                                            <tr>
                                                <td class="selector-perfil" width="10%">    
                                                    <select class="form-control" name="perfilAlta" id="perfiles">
                                                        <option value="0">Seleccione...</option>
                                                    </select>
                                                    <span id="errorPerfilAlta" style="display:none;color:red">Seleccione un perfil</span>                                                        
                                                </td>
                                                <td width="25%" style="padding-left:20px;">
                                                    <input type="submit" id="" data-toggle="modal" data-target="#modalAltaPerfil" class="btn button-primario hover_btn" value="Alta perfil">                                             
                                                    @*<input type="submit" id="btnExportar" class="btn button-primario hover_btn" value="Exportar perfil">*@
                                                    <input type="submit" id="btnGuardar" class="btn button-primario hover_btn" value="Guardar">
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                        <div class="panel panel-primary" id="tablaMenu">
                            <div class="panel-heading"><span id="titulo"></span></div>
                            <div class="panel-body" style="overflow-y: scroll; height: 600px">
                                
                                <table class="table table-striped" id="menu">
                                    <tr class="fondoGris">
                                        <th width="20%">Menú</th>
                                        <th width="30%"><span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-original-title="Seleccionará todos los submenús">&nbsp;</span> </th>
                                        <th width="55%"><span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-original-title="Seleccione submenú">&nbsp;</span> Submenú </th>
                                        @*<th class="text-left"><span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-original-title="Seleccione submenú">&nbsp;</span> </th>*@
                                    </tr>
                                    
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>	
    <!-- Modal ALTA Perfil -->
    <div class="modal fade" id="modalAltaPerfil" role="dialog">
        <div class="modal-dialog text-center">
            <!-- Modal content-->
            <div class="modal-content col-xs-10 col-sm-10 col-md-10 col-lg-10 ">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Alta de perfil</h4>
                </div>
              
                <div class="modal-body">
           
                    <div class="form-group row">
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 text-left">                        
                            <label>Perfil*</label>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-left">
                            <input type="text" name="nombre" class="form-control" id="nombrePerfil">
                          
                            
                            <span id="errorNombreAlta" style="display:none"><span></span></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">                    
                    <input type="button" id="AltaPerfil" class="btn button-primario " value="Aceptar" />                
                    <button type="button" class="btn button-primario" data-dismiss="modal">Cancelar</button>
                </div>
            </div>

        </div>
    </div>
    <!-- Modal FIN ALTA  PERFIL  -->
</body>
</html>

<script type="text/javascript">

    //Función que llena todo el menú y submenú para asignar a un perfil
    function checkSubMenu(control)
    {
        if (control.checked == true) {
            $('[id^="' + control.id + '-"]').attr('checked', true);
        }
        else {
           $('[id^="' + control.id + '-"]').attr("checked", false);
        }
    }

    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip({
            placement: 'center'

        });
        $('#tablaMenu').hide();

        $.ajax({
            type: 'GET',

            url: '@Url.Action("ListaPerfiles", "Usuario")',
            dataType: 'json',
            success: function (data) {
              
                for (var i = 0; i < data.length; i++) {
                    $('#perfiles')
                         .append($("<option></option>")
                                   .attr("value", data[i].idPerfil)
                                   .text(data[i].nombrePerfil));  
                }
            },
            error: function (emp) {
                alert('error');
            }
        });
    });


    $(function () {
        $('#AltaPerfil').click(function () { 
            $.ajax({
                type: 'GET',
                url: '@Url.Action("AltaPerfil", "PerfilUsuario")',
                dataType: 'json',
                data: { 'nombre': $('#nombrePerfil').val()},

                success: function (data) {
                    if (data) {
                        alert("Perfil creado con éxito");
                        jQuery("#perfiles").append("<option value=" + data + ">" + $('#nombrePerfil').val() + "</option>")
                        $('#modalAltaPerfil').modal('hide')
                    }else{
                        alert("Nombre de Perfil ya Existe");
                        $('#modalAltaPerfil').modal('hide')
                    }
                    },
                     error: function (emp) {
                         alert('error');
                         $('#modalAltaPerfil').modal('hide')
                     }
            });
        });
    });


    $(function  () {  
        $('#perfiles').change(function () {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetMenuPerfiles", "PerfilUsuario")',
                dataType: 'json',
                data: { 'strPerfil': $('#perfiles').val() },
                success: function (data) {
                    $('#tablaMenu').show();

                    var etiqueta = "Asignación de permisos para el Perfil - ";
                    $('#titulo').text(etiqueta + $("#perfiles option:selected").text());
                   

                    var cadenaMenu = '';
                    var cadenaSubmenu = '';                
                    var valorPadre;
                    var cuerpo_tabla = "";

                    //Llena el menu y submenu
                    for (var item = 0; item < data.listadoMenuByPerfil.length; item++) {

                        if (data.listadoMenuByPerfil[item].idPadre == null) {
                          
                            cadenaMenu = "<tr><td width='1px'><label for='selectall'>" + data.listadoMenuByPerfil[item].nombreMenu + "</label></td><td><input class='second' type='checkbox'" + data.listadoMenuByPerfil[item].atributo + " id=" + data.listadoMenuByPerfil[item].idMenu + " onclick='checkSubMenu(this)'/></td>";                
                            valorPadre = data.listadoMenuByPerfil[item].idMenu;
                        }
                        else {
                            valorPadre = 0;
                        }

                        if (valorPadre != 0) {
                            // Recorre toda la lista y encadena los submenus que pertenecen a cada menu
                            cadenaSubmenu = '';
                            cadenaCheck = '';
                            for (var sub = 0; sub < data.listadoMenuByPerfil.length; sub++) {
                                if (valorPadre == data.listadoMenuByPerfil[sub].idPadre) {                                  
                                    cadenaSubmenu += "<label><input type='checkbox' " + data.listadoMenuByPerfil[sub].atributo + " class='child' id=" + data.listadoMenuByPerfil[sub].idPadre + "-" + data.listadoMenuByPerfil[sub].idMenu + " />" + "&nbsp;&nbsp;&nbsp;&nbsp;" + data.listadoMenuByPerfil[sub].nombreMenu + "</label> <br>";
                                }
                            }
                            cuerpo_tabla = cuerpo_tabla  + cadenaMenu + "<td ><table>" + cadenaSubmenu + "</table></td><td ><table> </table>";
                        }
                    }
                    //borramos todo el cuerpo del menu para despues insertarlo de acuerdo al perfil.
                    $('#menu').html("");   
                    $('#menu').append(
                    '<tbody><tr class="fondoGris">' +
                    '<th width="20%">Menú</th>' +
                    '<th width="30%"><span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-original-title="Seleccionará todos los submenús">&nbsp;</span> </th>' +
                    '<th width="55%"><span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-original-title="Seleccione submenú">&nbsp;</span> Submenú </th></tr>'  + cuerpo_tabla)
                },
                error: function (emp) {
                    alert('error');
                }
            });
        
        });
    });


    $('#btnGuardar').click(function () {
        var cadena_valores = '';
        $("input:checkbox:checked").each(function () {
            //Obtiene una cadena de los idMenu seleccionados
            cadena_valores = cadena_valores + $(this)[0].id.split("-").pop() + '|';         
        });

        $.ajax({
            type: 'GET',
            url: '@Url.Action("AltaPerfilMenu", "PerfilUsuario")',
            dataType: 'json',
            data: { 'strPerfilMenu': cadena_valores, 'strPerfil': $('#perfiles').val() },       
            success: function (data) {
                if (data) {
                    alert("Menú asignado a Perfil correctamente");
                    jQuery("#perfiles").append("<option value=" + data + ">" + $('#nombrePerfil').val() + "</option>")
                    $('#modalAltaPerfil').modal('hide')
                } else {
                    alert("Ha ocurrido un error, Consulte con el administrador.");
                }
            },
            error: function (emp) {
                alert('error');
            }
        });
    });
</script>